version: '2'
services:
  database:
    build:
      context: .
      dockerfile: ./docker/database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: ./docker/api
    ports:
      - 8000:8000
    links:
      - database
    environment:
      - SSHSCAN_API_HOST=api
      - SSHSCAN_API_PORT=8000
      - SSHSCAN_API_ALLOWED_PORTS=22
      - SSHSCAN_API_AUTHENTICATION=false
      - SSHSCAN_DATABASE_HOST=database
      - SSHSCAN_DATABASE_NAME=ssh_observatory
      - SSHSCAN_DATABASE_USERNAME=sshobs
    networks:
      - default
    restart: always
    depends_on:
      - "database"
    stdin_open: true
    tty: true
    working_dir: /app
    command: ["/app/bin/ssh_scan_api"]
  worker:
    build: https://github.com/mozilla/ssh_scan_worker.git
    links:
      - api
    networks:
      - default
    depends_on:
      - api
    restart: always
    working_dir: /app
    command: ["/app/bin/ssh_scan_worker"]