# The interface you would like the API to bind to, by default is assumes 127.0.0.1
# Uncomment the below line if you want to intentionally host the service on all interfaces
#bind: 0.0.0.0

# The TCP port that the service should use
port: 8000

# API Tokens (a crude mechanism for adding auth to your API)
#authentication: true
authentication: false

# If authentication is to true, the authentication tokens you generate below
# will be required to access certain API functions.
#
# Generate a new token using Ruby's Secure random uuid
# $ ruby -r securerandom -e 'puts SecureRandom.uuid'
#
# users:
#   - username    : starlord
#     token       : INSERT_GROOT_TOKEN
#   - username    : groot
#     token       : INSERT_GROOT_TOKEN
#   - username    : gamora
#     token       : INSERT_GAMORA_TOKEN

# workers:
#   - worker_name : worker1
#     token       : INSERT_WORKER1_TOKEN

# Define database configuration
# MongoDB Example
# database:
#   type: mongodb
#   name: ssh_scan
#   queue_db_name: ssh_scan_queue
#   server: 127.0.0.1
#   port: 27017

# SQLite Example
database:
  type: sqlite
  file: ssh_scan.db
  queue_db_file: ssh_scan_queue.db
